#!/usr/bin/env bash

# exit if a command fails
set -e

# rebuild darwin
darwin-rebuild switch --flake ~/nix#ruarqs-air

# collect garbage
read -p "Run nix-collect-garbage? (y/n): " -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
  echo ""
  tput rmam
  nix-collect-garbage -d 2>&1 | awk '{ printf("\r\033[K%s", $0); fflush(stdout); last=$0 } END { printf("\r\033[K%s\n", last) }'
else
  echo ""
fi
